name: Update playlist

on:
  schedule:
    - cron: '25 1 * * 1-6'   # 周一至周六 9:25 CST -> 1:25 UTC
    - cron: '20 2 * * 1-6'   # 周一至周六 10:20 CST -> 2:20 UTC
    - cron: '35 3 * * 1-6'   # 周一至周六 11:35 CST -> 3:35 UTC
    - cron: '30 4 * * 1-6'   # 周一至周六 12:30 CST -> 4:30 UTC
    - cron: '15 7 * * 1-6'   # 周一至周六 15:15 CST -> 7:15 UTC
    - cron: '15 8 * * 1-6'   # 周一至周六 16:15 CST -> 8:15 UTC
    - cron: '10 9 * * 1-6'   # 周一至周六 17:10 CST -> 9:10 UTC
    - cron: '10 11 * * 1-6'  # 周一至周六 19:10 CST -> 11:10 UTC
  
  workflow_dispatch:
    inputs:
      param:
        description: 'parameter'
        required: false
        default: ''

env:
  COOKIES: ${{ secrets.COOKIES }}
  TZ: Asia/Shanghai
  PYTHONIOENCODING: utf-8

jobs:
  update-playlist:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main  # 克隆当前仓库
        with:
            ref: 'action-update'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Update playlist
        run: |
          pwd
          $cookies = '${{ secrets.COOKIES }}'  # 获取 Secret 内容，注意使用单引号避免解析错误
          Set-Content -Path "cookies.json" -Value $cookies
          python init.py -l -hl

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Update playlist at $(date -u '+%Y-%m-%d %H:%M:%S')"
          git push origin action-update
